/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#154539",
        "secondary": "#4a654f",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-dim": "#dadada",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#404945",
        "outline": "#717975",
        "outline-variant": "#c0c8c4",
        "secondary-container": "#c9e7cc",
        "on-secondary-container": "#4e6953",
        "primary-container": "#2f5d50",
        "on-primary-container": "#a3d4c3",
        "primary-fixed": "#bceddc",
        "primary-fixed-dim": "#a0d1c0",
        "secondary-fixed": "#cceacf",
        "secondary-fixed-dim": "#b0ceb4",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#a0d1c0",
        "tertiary": "#3f3e38",
        "tertiary-container": "#56554f",
        "on-tertiary-container": "#cdcac2",
        "tertiary-fixed": "#e6e2da",
        "tertiary-fixed-dim": "#c9c6bf",
        "on-tertiary": "#ffffff",
        "surface-tint": "#396759",
        "surface-variant": "#e2e2e2",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "section-gap-sm": "40px",
        "section-gap-lg": "80px",
        "container-max": "1200px",
        "unit": "8px",
        "gutter": "24px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      borderRadius: {
        "sm": "4px",
        "md": "8px",
        "lg": "12px",
        "xl": "16px",
        "2xl": "24px",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
